version: '3'
services:
    app:
        container_name: spice_cast
        restart: always
        build : .
        ports : 
            - '4000:4000'
        links : 
            - mongo
        networks:
            - spice_cast_app-network

    networks:
        spice_cast_app-network:
            external: true