version: '3'
services:
    spicecast:
        container_name: Spicecast
        image: nodejs
        build : .
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        volumes:
            -./:/usr/src/app
        ports : 
            - '4040:4040'
        networks:
            - spicecast-network
        
    mongo:
        container_name : mongo
        image: mongo
        restart: unless-stopped        
        env_file: .env  
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:
            - mongo-data:/data/db
        ports : 
            - '27017:27017'
        networks:
            - spicecast-network